version: '3'

services:
  dndsolution.api:
    image: dnd_api
    container_name: dnd_api
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: K:/DndSolution/Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development # debug runs in development mode
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Rjkz1234 # password used when making the cert, without curly braces
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
      - ~/.aspnet/https:/https:ro
    networks:
      - backend
        
  postgres:
    container_name: dnd_db
    image: postgres
    environment:
      POSTGRES_USER: doterfather
      POSTGRES_PASSWORD: doterfather
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - backend
    restart: unless-stopped
  
  
  
networks:
  backend:
    driver: bridge

volumes:
  postgres:
